@host = http://localhost:80

### Create user
POST {{host}}/users
Content-Type: application/json

{
  "name": "John Doe",
  "email": "john.doe@example.com"
}

### Create order
POST {{host}}/orders
Content-Type: application/json

{
  "userID": "1",
  "price": 1000
}
